### ISSUE TITLE
works on tivimate? question

### ISSUE THREAD

**Issue by Toei79** [K-vanc/Tempest-EPG-Generator#11] opened 2023-01-23 18:30 UTC
hi amazing tool! curve learning process

i get xml file, but on tivimate just get the first channel,  i do from zap2it from one script, i get same situation but i add to tvheadend and tvheadend fix it,
 
idk but with some xml files adding channel list before the epg in the xml , tivimate can detect it

other question its possible do automated i mean using maybe crontab?

**Comment by K-vanc** [comment] 2023-01-23 18:59
Hi and thanks for using Tempest. Since there is no restriction on channel tag and programme tag order as per Xmltv standard, Tempest uses;

Ch tag1
Programme tags of ch1
.
.
Ch tagN
Programme tags of chN 

Order by default. Some players such as tivimate has faulty epg channel parser and mandates users to load xmltv files which all channel tags listed at top. If you need this tag sequence all you need to do is choosing your configuration file on Tempest Configurator and enable "Channel-Lister" option under File Configuration tab.

![20230123_214259.jpg](https://user-images.githubusercontent.com/97025515/214124993-0b876051-ea9d-41e2-9550-8b3217f194c0.jpg)

For other question, yes, Tempest supports scheduled operations and crontab. For linux, you can directly add as command or create a sh file(for more complex operations such as copy/paste Some other location etc.).And same can be done with bat file on Windows. You can find detailed info about cli parameters on page 49 of TempestWIKI.pdf

![Screenshot_20230123-215727_Drive.jpg](https://user-images.githubusercontent.com/97025515/214126200-2597c1d8-01cc-43e5-a163-43280a164be5.jpg)

**Comment by Toei79** [comment] 2023-01-23 21:45
yea i did it, and i able to see list channels prior to epg , enabling channel lister,  unfortunely for me it still do the same tivimate.  
idk i have small script for radio stations and runs fine same estructure , but its really small some manual, i tried with zap2it adding on top and see it works and not , it needs pass through tvheadend to work. 

im going to check guide

**Comment by K-vanc** [comment] 2023-01-24 02:20
Hi again. I dont have tivimate but I added channel lister option due to request of my users who are using tivimate and they all confirmed that it resolved the issue. It turns xmltv file into traditional order and there is no special thing except location of channel tags so I dont know what else Could be the problem for you, may be clearing cache of tivimate or uninstall/reinstall?

**Comment by Toei79** [comment] 2023-01-24 03:08
idk then im going to try in other device , but its some that happened with other epg that i get. just get the first channel nothing else. thank you ! i gonna check

**Comment by K-vanc** [comment] 2023-01-24 04:06
Please share the results. Also maybe the users I mentioned may share their experince about tivimate here in order to help if some kind of setting etc. is needed.

**Comment by Toei79** [comment] 2023-01-24 04:13
> Please share the results. Also maybe the users I mentioned may share their experince about tivimate here in order to help if some kind of setting etc. is needed.

hi! yea you was right. 

its working, in the other device, now my headache its clear something ? i mean delete some important data.

nvidia shield tivimate get the issue

tivo 4k stream tivimate works perfectly with epg!

but yea i getting this issue before now understand issue its with cache or something.

**Comment by Toei79** [comment] 2023-01-24 04:15
other question sometimes some ini files are down? just try ones from colombia there are two but one with radios freeze , check page online freeze too.  but yes also you have tvguide you can get data from there too amazing!

**Comment by Toei79** [comment] 2023-01-24 04:55
i clear cache and that fix it. but every time you change add a channel to epg you will need that.  also you need close app tivimate app, if you clear cache and not close its not gonna work,

**Comment by K-vanc** [comment] 2023-01-24 06:44
Good to hear it works for you. What you mentioned is a problem with tivimate so it could be better to contact with their development team, as I told you i dont have tivimate but as a general when app updates/populates epg file, changes shall be available without need of a cache clearance everytime.

For Colombia siteconfig, i dont know which one you tried but as discussed on other open issue topic, [ENC][EX] prefixed siteconfigs may block your ip temporarily in case of too many individual request (not talking about regular grabbing with several channels from same siteconfig) in a short time. I am planning to patch them all with a new solution within this week.

And finally, yes you can create your own siteconfigs for any source(local/remote) in any format(html, xml, json, xls, txt and even pdf) by using Siteconfig Maker. You need to find data containing url of source and add necessery header if any to defined places in Siteconfig Maker. Then you can parse captured data with regex as show elements. There are some basic examples about shows elements and url parameters in TempestWIKI.pdf. You can also check inside and debug unlocked siteconfigs with Debugger. Also you can make a request in a new topic and i will try to share completed siteconfig when I have time

**Comment by K-vanc** [comment] 2023-01-25 04:06
It is working, There was a minor change since the time I made siteconfig so uploaded revised version. Channel list also updated so do not forget use updated channels. 

Please confirm then I will close the issue

**Comment by Toei79** [comment] 2023-01-25 21:39
> It is working, There was a minor change since the time I made siteconfig so uploaded revised version. Channel list also updated so do not forget use updated channels.
> 
> Please confirm then I will close the issue

I check  tonight  so I need update the site ini folder? Download last one and replace this one?

That link its not working  at least for me I'm in usa.

**Comment by Toei79** [comment] 2023-01-26 00:39
> It is working, There was a minor change since the time I made siteconfig so uploaded revised version. Channel list also updated so do not forget use updated channels.
> 
> Please confirm then I will close the issue

it fixed, thank you

question i know other project where runs epg from tvmaze , it creates channels with local videos of shows, movies etc, but epg dont get right,  i know this out of here, you can take a look? if not i understand thanks

**https://github.com/deanochips/HLS-XMLTV---Home-Broadcasting**

any way you mind i buy a coffe? i appreciate this project.

**Comment by K-vanc** [comment] 2023-01-26 04:39
Hi. sorry but I cannot help much on that since it's not my code and to say and/or fix anything I need to focus/work on it and spend some time but unfortunately I am using all my free time on Tempest. I just had a quick look to epg generation code and noticed timezone is hard coded as +0000, tvmaze request seemed valid to me. If you are facing with some mismatch on the timeline of shows, hardcoded timezone may be an issue. Try to set with your epg player's timeshifter (if any) to align it with +0000. Maybe it solves. I dont know if their parser is still working correctly. If you have an issue as cannot find the shows, you may try to rename your streams as shown on tvmaze webpage so it will increase catching accuracy. These are all I can say..
Thanks for your offer. If you want, you may use 1 of the one-time sponsor tiers you want or via wise transfer from bottom of main page. 
Anyway, I am closing the issue as completed.

**Closed by K-vanc** 2023-01-26 04:39 UTC
Labels: question

**Comment by Toei79** [comment] 2023-01-26 14:43
wish you use paypal pretty sure easier route,

thanks you helps a lot on that one.

**Comment by K-vanc** [comment] 2023-01-26 14:53
Thanks, I dont have paypal since it is not available in my region but github sponsorship currently allows people to send money with paypal and transfere it to my account.

**Comment by Toei79** [comment] 2023-01-27 05:23
> Thanks, I dont have paypal since it is not available in my region but github sponsorship currently allows people to send money with paypal and transfere it to my account. You may reach from below link;
> 
> https://github.com/sponsors/K-vanc?frequency=one-time&sponsor=K-vanc

send it! thanks :)
