### ISSUE TITLE
SiteConfig Request

### ISSUE THREAD

**Issue by Wangliann** [K-vanc/Tempest-EPG-Generator#31] opened 2023-07-26 01:58 UTC
Hey K-Vanc,
I'm sorry to submit the pull request again, because the [tbc.net.tw](https://www.tbc.net.tw/epg/Channel?channelId=054)  has been completely unavailable in recent days even I used the correct IP. 
Can you help me add the siteconfig for https://mod.cht.com.tw/bepg2/ 
Thanks

**Comment by K-vanc** [comment] 2023-07-26 04:26
added to Taiwan folder

**Comment by Wangliann** [comment] 2023-07-26 04:33
Great! Thanks for quick response

**Comment by Wangliann** [comment] 2023-07-26 04:45
![QQ截图20230726124446](https://github.com/K-vanc/Tempest-EPG-Generator/assets/66773773/dfba0011-9b6a-43a4-8e21-43196dad8d3d)
error:0A000126:SSL routines::unexpected eof while reading

**Comment by K-vanc** [comment] 2023-07-26 05:36
this is an error related with ssl certificates of website. It was ignored by php/curl-openssl libraries on previous versions but new versions are terminating the execution. Unfortunately, there is nothing I can fix from Tempest or siteconfig site. It works on my Windows with php 7.4.33 and I am receiving same error if I switch to php 8.2.1. If you are using some UNIX OS, editing /etc/ssl/openssl.cnf as

CipherString = DEFAULT:@SECLEVEL=0

and reloading your php server will make it run but I personally not recommend to do that. For Windows, I don't know any solution except downgrading your php version.

In the end, this is an error that shall be fixed by website since the problem is related with their sll certs.

**Comment by Wangliann** [comment] 2023-07-26 06:29
I downgraded to the same php version as yours on windows, but it still prompts：OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mod.cht.com.tw:443

**Comment by Wangliann** [comment] 2023-07-26 06:40
Good news, when I changed the network everything worked fine

**Comment by K-vanc** [comment] 2023-07-26 06:45
it is not actually related with php version but related with curl/opensll libraries. Each version + php server combination has different library versions. Hard to guess which is fine and which is not. I am using php's built in development server with below libraries;

cURL Information => 7.70.0
OpenSSL Library Version => OpenSSL 1.1.1s 1 Nov 2022

and this is the result;

![image](https://github.com/K-vanc/Tempest-EPG-Generator/assets/97025515/415449a1-e5c6-40f4-8c45-d4b36419de5a)

Btw, now you reported another error than unexpexted eof while reading. SSL_ERROR_SYSCALL usually an issue related with your network or firewall. Something in your network(such as an antivirus) may be blocking your connection to website. it is quite possible since I am also receiving privacy error on google while trying to open that website

**Comment by K-vanc** [comment] 2023-07-26 06:52
ah, yes, changing network may also help for getting rid of network restrictions :) 

anyway, good to hear, it is ok now. Enjoy

**Comment by K-vanc** [comment] 2023-07-27 11:42
i think issue resolved and I can close the topic, right?

**Closed** 2023-07-29 03:49 UTC
Labels: Request
